# Generated by Django 2.2 on 2020-11-16 19:54

from django.db import migrations, models
import formtest.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, validators=[formtest.models.validateLengthGreaterThanTwo])),
                ('last_name', models.CharField(max_length=45, validators=[formtest.models.validateLengthGreaterThanTwo])),
            ],
        ),
    ]
